version: '3.8'

services:
  vrihi:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-video-factory:latest
    container_name: vrihi_container
    volumes:
      - .:/manim
      - ../Videos/production:/manim/../Videos/production
    env_file:
      - .env
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command: vrihi.sh
